### ISSUE TITLE
Missing breathing room on top of the graph

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-analytics-ui#6]
The max value should not be on the border of the graph:

<img width="931" alt="screen shot 2015-07-19 at 4 05 49 pm" src="https://cloud.githubusercontent.com/assets/246910/8768318/36a28296-2e30-11e5-8006-8f37758e95e3.png">

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill-analytics-ui/pull/11.
