### ISSUE TITLE
Lines should not start from 0 axis but instead link points together

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-analytics-ui#7]
<img width="713" alt="screen shot 2015-07-19 at 4 08 55 pm" src="https://cloud.githubusercontent.com/assets/246910/8768327/88d72cce-2e30-11e5-83c5-dfbfef2740ca.png">

**Comment by pierre** [comment]
Fixed by https://github.com/killbill/killbill-analytics-ui/pull/11.
